
backend:
  name: git-gateway
  repo: akhil-naidu/gatsby-theme-nehalem

media_folder: demo/content/posts/blog/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: "demo/content/posts/blog"
    create: true
    slug: "{{slug}}"
    
    fields:
      - { name: title, label: Title, widget: string }
      - { name: path, label: Path }
      - { name: tags, label: Tags, widget: list }
      - { name: metaImage, label: Meta Image, widget: image }
      - { name: featuredImage, label: Image Location, widget: string }
      - { name: excerpt, label: Excerpt, widget: string }
      - { name: created, label: Created, widget: date }
      - { name: updated, label: Updated, widget: date }
      - { name: body, label: Body, widget: markdown }

collections:
  - name: page
    label: Page
    folder: "demo/content/pages"
    create: true
    slug: "{{slug}}"
    
    fields:
      - { name: title, label: Title, widget: string }
      - { name: path, label: Path } 
      - { name: excerpt, label: Excerpt, widget: string }
      - { name: body, label: Body, widget: markdown }
