backend:
  name: github
  repo: akhil-naidu/gatsby-theme-nehalem
  branch: 

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
